### ISSUE TITLE
FR: Warning & path to resolve Lockfile Creation issues

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1050]
**Is your feature request related to a problem? Please describe.**
User can run into a problem with lockfiles being already in use (through unexpected shutdown f.e.) 

**Describe the solution you'd like**
A warning if there are problems & way to disable the creation of the lockfiles by setting this flag, and resolve the problem / or alternatively a link to documentation that describes the process to do that. 

Example: If Teku dies the container doesn't automatically start anew through this problem

**Comment by daGscheid** [comment]
In a newest example, one of our users - Noman - has run into a lock file issue regarding lodestar

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/7771735d-5f0f-4858-a27b-bb0eeb82e57e)

Being the first time a user has run into it, we should also add a path to resolve this issue for Lodestar

**Comment by M4r71nW** [comment]
Due to recent changes how lonestar validator client is handling lockfiles: https://github.com/ChainSafe/lodestar/pull/6363 , it’s unlikely that users will experience this issue in the future. 
Since version 1.15.1 they are using the "proper-lockfile" package which handels “lockfiles”  as directories. 
>The notable difference is that lockfiles will be considered stale after 10 seconds if process is not running

also users who upgraded from previous versions and for some reason their previous .lock files are not cleaned up should no longer experience issues: https://github.com/ChainSafe/lodestar/pull/6450

Should a user somehow still experience an issue witch an deprecated lockfile they should add the `--force=true` flag into their validator-client config like it’s described here: https://chainsafe.github.io/lodestar/contribution/dev-cli/#-force
(Use with caution)
