### ISSUE TITLE
[Bug]: Syncing Dashboard Component stays "On Hold" despite client syncing

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1236]
### Contact Details

-----

### Describe the bug!

Client Status Sync stays on "Hold" in the Sync Component, despite logs looking good. 

Problem spotted with Nimbus by one of our Discord users named Luc1d

### Attach a Screenshot!

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/b98dfb31-2def-4ea9-8267-6295b8e04829)

### Expected Behaviour

The sync component works as intended and shows the current sync status

### Help us reproduce your bug!

1) Install A Node
2) Go to Control Page 
3) Check Sync Dashboard Component 
4) Check Logs of Clients syncing

### Launcher Version

rc.18.1

### Desktop OS

MacOS

### Node Server OS

Ubuntu 22.04

### Affected Service

Nimbus 

### Relevant log output

```shell
-------
```

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by daverolo** [comment]
This has nothing to do with Nimbus. If the SyncStatus Widget shows "on hold" then the lowerslot and higherslot are both zero. **That means we do not have any data from Prometheus**. I spotted this behaviour also when i upgraded my Teku testing node but did not give much attention to it since i usually impair my nodes heavily during development.

**Comment by daverolo** [comment]
Futher versions from Nimbus report stats properly to Prometheus. For execution clients a workaround was possible, therefore they got the separate issue #1274 which is fixed with #1275. Consensus clients needs to report their stats properly - there is no workaround possible.
