### ISSUE TITLE
[FR]: Supporting Ubuntu 24.04

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#1591]
### Describe your idea

Support for Ubuntu 24.04 (not released yet). Daily builds: https://cdimage.ubuntu.com/daily-live/current/

### Considered Alternatives?

-

### Additional Context

-

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by M4r71nW** [comment]
https://cdimage.ubuntu.com/ubuntu-server/daily-live/current/

**Comment by M4r71nW** [comment]
1 click installer with stereum-launcher can not complete successful on Ubuntu Server 24.04. "noble numbat" because
the ansible PPA, which is added in
**NodeConnection.js Line 156**  does not exist:
```
try {
        installPkgResult = await this.sshService.exec(
          "apt update &&\
                    apt install -y software-properties-common &&\
                    add-apt-repository --yes --update ppa:ansible/ansible &&\
                    apt install -y pip ansible tar gzip wget git"
        );
      }
```
the ppa for this Ubuntu Version does not exist:
[https://ppa.launchpadcontent.net/ansible/ansible/ubuntu/dists/](https://ppa.launchpadcontent.net/ansible/ansible/ubuntu/dists/)

`[debug] stderr got data E: The repository 'https://ppa.launchpadcontent.net/ansible/ansible/ubuntu noble Release' does not have a Release file.`

however ansible is still installed from the official apt repository, but
later the setup is still failing because in the playbook:
**docker-ubuntu.yaml Line 30**
```
- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
```
the play also needs this ansible ppa which does not exist and so the playbook run fails:
```
PLAYBOOK: /opt/stereum/ansible/controls/genericPlaybook.yaml
TASK: Add Docker Repository
ACTION: apt_repository
CATEGORY: FAILED
DATA: {"msg": "Failed to update apt cache: E:The repository 'https://ppa.launchpadcontent.net/ansible/ansible/ubuntu noble Release' does not have a Release file., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://download.docker.com/linux/ubuntu noble Release' does not have a Release file.", "_ansible_no_log": null, "changed": false}
```
error log from the launcher:
```
[error] Can't run setup playbook:  Error: Failed running 'setup': <stderr empty>
    at Object.runPlaybook (/tmp/.mount_StereupEUKt6/resources/app.asar/index.js:8:550906)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.prepareStereumNode (/tmp/.mount_StereupEUKt6/resources/app.asar/index.js:8:549426)
    at async Object.prepareNode (/tmp/.mount_StereupEUKt6/resources/app.asar/index.js:8:573283)
    at async /tmp/.mount_StereupEUKt6/resources/app.asar/index.js:8:587139
    at async node:electron/js2c/browser_init:2:98069
```

**Comment by daGscheid** [comment]
25th of April according to 
https://9to5linux.com/looks-like-ubuntu-24-04-lts-will-be-powered-by-linux-kernel-6-8#:~:text=Ubuntu%2024.04%20LTS%20is%20slated,the%20GNOME%2046%20desktop%20environment.
