### ISSUE TITLE
Make execution client available for MetaMask

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#386]
MetaMask can connect to a custom Ethereum node (execution client). Users should be able to use their own nodes for MetaMask. To make this possible there are a few steps to make this happen:

- [x] Open SSH tunnel for execution client's API, see https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/#reaching-rpc for what APIs need to be accessible
- [x] Propagate the local port to the user
- [x] Save the port to the config file of Stereum Launcher to always use the same one even after restart. Also prevent other Stereum Launcher SSH tunnels (Grafana, Prometheus, etc.) to use this same port. Alert the user when the port is in use and propagate a new one, saving it again.
- [x] Tutorial on how to connect MetaMask to the SSH tunnel port, here's some reading https://metamask.zendesk.com/hc/en-us/articles/360015290012-Using-a-Local-Node

@daGscheid please provide some UI for:
- Button to open the tunnel
- Show the user the port#, maybe even the whole url, also when the port changed.

**Comment by daGscheid** [comment]
I would feature this function to set an Execution RPC Endpoint
For reference: 
![image](https://user-images.githubusercontent.com/82385103/177056158-45559685-27b3-410d-8f7e-e0d376fcffb5.png)


This would follow the same logic as the other buttons. Expanding when pressed and the user is asked for confirmation/input (will discuss more with you guys tomorrow, of what this entails in this example)  
Whenever pressing yes, the a task is started. The border of the button turns blue then green and stays green as long as a RPC endpoint is enabled. 


![image](https://user-images.githubusercontent.com/82385103/177056102-85313ffd-7922-48a3-8ede-233f47c7eb46.png)
(I am also playing with the thought of displaying the port under the text)

To further first sight clarity, I would like to use one of the empty dashboard elements. 
For the Execution Client RPC Endpoint, as well as the Consensus Client API. 
If they are in use, it would look something like this: 

https://media.discordapp.net/attachments/903204363667910656/993250306139881552/unknown.png

In my mind, as a QoL feature - clicking the elements could copy the URLs. 

Will discuss tomorrow with you and come back with a clearer plan!

**Comment by daGscheid** [comment]
- in discussion if we should add an on / off switch in the dashboard component

**Comment by daGscheid** [comment]
Changed the plan. Button are out with #562 the plan is now to tackle it in #335 

For reference: 
![EN - NODE TAB - HOME - ACTIVE – 3](https://user-images.githubusercontent.com/82385103/180004206-027f966b-f839-4f21-b30b-dcbe81fc4b7e.png)


The Dashboard still will feature a similar component #562

**Comment by daverolo** [comment]
The following is done (currently for a **SINGLE** CL/EL service):
- Open SSH tunnel 
- Propagate the local port to the user
- Save the port to the config

### For RPC-API (EL)
The mapped port on the node is always the same (8545).
The port provided to the user (Desktop) is by default 8545 (if available, otherwise the port counts up +1 until available)
The full URL (usually http://127.0.0.1:8545) is provided thru the RPC-ENDPOINT Widget:
![grafik](https://user-images.githubusercontent.com/107847185/197157578-0ad81d34-a5ba-4bbd-8d44-1ca48010c67e.png)

### For BEACON-API (CL)
The mapped port on the node is always the default of the CL (e.g.: 5051 for Teku, 3500 for Prysm,..)
The port provided to the user (Desktop) is by default 5545 (if available, otherwise the port counts up +1 until available)
The full URL (usually http://127.0.0.1:5545) is provided thru the DATA-API Widget:
![grafik](https://user-images.githubusercontent.com/107847185/197157830-ee6acedb-8852-4b10-b143-74c3c7295009.png)

### Open

Support for multiple CL/EL services, respectively multiple tunnes, is and open task which will be done with #841.

**Comment by daGscheid** [comment]
Currently syncing the node to provide the tutorial - as is part of #686

**Comment by daGscheid** [comment]
@SasaRis Currently working on a tutorial. Please let us know when you updated #686  with necessary links reharding point 4.
