### ISSUE TITLE
FR: Besu pruning settings

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#723]
**Is your feature request related to a problem? Please describe.**
Right now there is no user friendly way to enable/disable pruning for Besu.

**Describe the solution you'd like**
Let the user choose to enable (default) or disable pruning: https://besu.hyperledger.org/en/stable/public-networks/concepts/data-storage-formats/#pruning 

**Describe alternatives you've considered**
No pruning would mean more storage resources used.

**Additional context**

**Comment by daGscheid** [comment]
For Besu, I would reuse the component we also used in #719. Important however is that we difference them somehow because of their different functionality. 

This would look something like this: 
![SERVICE_SETTING_MODULE](https://user-images.githubusercontent.com/82385103/199584533-31334a08-2c3d-49da-b984-fe4469350811.png)

With the icon used being this: 
![AUTO Prunning](https://user-images.githubusercontent.com/82385103/199584138-055143ad-0fd9-4948-993a-9b1623c3c3ba.png)

**Comment by stefa2k** [comment]
the icon is great, but it's hard to read because it's so small

**Comment by NeoPlays** [comment]
Pruning is being deprecated for `BONSAI` format and is currently not being updated.

Adding `--pruning-enabled=true` to the config just prompts a warning in the logs, which basically says that pruning is not being used.

All Besu Stereum nodes till today are deployed with `BONSAI` but pruning is only supported with `FOREST` format.

Changing the format while syncing/ while fully synced can cause problems with existing downloaded states:
[issue](https://github.com/hyperledger/besu/issues/3743)

Do we even want to use `FOREST` with pruning instead of `BONSAI`?
Bonsai already uses less space than `FOREST` and is faster most of the time. [docs](https://besu.hyperledger.org/en/stable/public-networks/concepts/data-storage-formats/#forest-of-tries)

`--pruning-enabled=true` will still be deployed to all existing and new Stereum nodes because it doesn't cause any problems. If a experienced user decides to use `FOREST`, he then can easily switch pruning on and off from the service settings
