### ISSUE TITLE
FR: connect to servers with 2FA enabled 

### ISSUE THREAD

**Issue by adv0r** [stereum-dev/ethereum-node#729]
Solo staker here, followed good practices (as suggested on [CoinCashew](https://www.coincashew.com/coins/overview-eth/guide-or-how-to-setup-a-validator-on-eth2-mainnet/part-i-installation/guide-or-security-best-practices-for-a-eth2-validator-beaconchain-node#setup-two-factor-authentication-for-ssh-optional) btw) and enabled Google Authenticator 2FA to connect via ssh: `libpam-google-authenticator`

**Comment by daGscheid** [comment]
We hopefully finally tackle this, because it would be nice to have.

This tutorial gives a basic overview of how to setup 2FA with a remote server. 
https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-18-04

To support this option in Stereum we were thinking about the following flow:

The Google will be integrated as an additional service installable service:

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/febb9cd5-3d72-4116-9b09-f97043b32b34)

Once installed the modal will be available on the top, revealing, when clicked, the following options:

![2FA - 002](https://github.com/stereum-dev/ethereum-node/assets/82385103/2715638e-814a-4900-bc2d-f62d664929f4)

<br>

The options presented here are:

1) To setup a completly new 2FA 
2) To import an existing back-up of your secret key via the `.google-authenticator` file

<br>

![2FA - 003](https://github.com/stereum-dev/ethereum-node/assets/82385103/9bdba469-a706-46e7-be01-9343467230b5)

<br>

When generating a new 2FA, before the key is able to be generated, the user has to decide if they want to use a time based token (which is recommended)

Clicking the "Generate Key" button leads to the next step 

<br>

![2FA - 004](https://github.com/stereum-dev/ethereum-node/assets/82385103/85555e49-b77a-4a55-a988-653bc3bb66e0)

<br>

After generating the new secret key, the user continues to the modal above.

Here the user should back up his secret key (which can be later used for importing it in the first step). 

Below it the user is able to conenct his Google Authenticator via the QR & should write down the all secrets presented. 
This includes a secret key, a verification code & the scartch codes necessary to regain the ability to authenticate themselves

Before the user can continue he has to check the "Confirm that you sucessfully set up the Google Authenticator!" box to make sure he doesn't lock himself out of his own remote server (lol) 

Clicking the button, writes the key and options to the .google_authenticator file. If the user says closes it, the program quits and nothing is written, which means the authenticator won’t work

<br>

![2FA - 005](https://github.com/stereum-dev/ethereum-node/assets/82385103/aded19c4-c1dd-4d91-a945-e94b31f04a3d)

<br>

Now having actually setup the 2FA, the user is able to modify some options. Here they are also recommended options, which are shown above.  Having configured this, the user is now completly finished with the setup process

<br>

![2FA - 006](https://github.com/stereum-dev/ethereum-node/assets/82385103/4564e4df-230c-4ca6-aea4-2e0ab6387eb9)

<br>

From there on onwards, the modal above is what greeets the user whenever he click the symbol in the header. 

Here the user is again presented with two options: 


![2FA - 007](https://github.com/stereum-dev/ethereum-node/assets/82385103/9a46e8bb-4ff9-4aee-b812-faefe0c990bf)

1) Change the configuration (as in the step before) 


![2FA - 008](https://github.com/stereum-dev/ethereum-node/assets/82385103/46c0bafb-907a-42a4-92f9-cc595e40b382)

2) OR delete the 2FA authentification, confirming it by clicking the button again. 


----

After this setup, as soon as the user logs in...

![LOGIN_ENGLISH – 6](https://github.com/stereum-dev/ethereum-node/assets/82385103/074abfcf-3c98-4674-aaea-10eb1815375b)

... they will be presented with following modal:

![LOGIN_ENGLISH – 7](https://github.com/stereum-dev/ethereum-node/assets/82385103/c0c00660-3b7d-4459-9279-395ad67ae996)

Where they will have to enter the OTP generated by the Authenticator

**Comment by daGscheid** [comment]
Having discussed with @PatrickRL. Will make slight adaptions to the setup process. Instead of having to add a service we decided to just make it part of Stereum. 

2FA will join as an extra tab in the server management

![2fa](https://github.com/stereum-dev/ethereum-node/assets/82385103/e8aa9df7-a658-481d-8aa2-718271127988)

![2FA – 2](https://github.com/stereum-dev/ethereum-node/assets/82385103/406e7602-ede0-4899-80f4-854caf4ed0df)

Having to save the backup:
![2FA – 3](https://github.com/stereum-dev/ethereum-node/assets/82385103/a328502d-bf24-4b6f-b753-1d462c8dc7ae)


Having to confirm that the setup was sucessfully:

![2FA – 4](https://github.com/stereum-dev/ethereum-node/assets/82385103/a951b0c8-13a4-4f45-af14-f43e514e699b)

![2FA – 5](https://github.com/stereum-dev/ethereum-node/assets/82385103/001b8c9c-9cf4-45aa-8a40-a0ead5af708d)


![2FA – 6](https://github.com/stereum-dev/ethereum-node/assets/82385103/61b86bd1-5d83-4b14-9d8a-37512cf9687c)

**Comment by adv0r** [comment]
niceeeeeeee
